package vedam.subkuch.ui.matrimonial.models

import android.os.Parcel
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import vedam.subkuch.db.chat.LatestChat
import vedam.subkuch.network.models.UserDetail.ImageObject

@Parcelize
data class DatingProfile(
    var ProfileId: String?,
    var ComplexionName: String?,
    var UpdatedDate: String?,
    var Income: String?,
    var Latitude: String?,
    var Gender: String?,
    var MothertongueName: String?,
    var AccessPin: String?,
    var DOB: String?,
    var Dating: String?,
    var DoshamName: String?,
    var BodyTypeid: String?,
    var MasterCastName: String?,
    var AnualIncomeid: String?,
    var QualificationName: String?,
    var Gotraid: String?,
    var Nakshakraid: String?,
    var CityName: String?,
    var Longitude: String?,
    var countryid: String?,
    var ReligionName: String?,
    var motherTougeid: String?,
    var GotraName: String?,
    var CreatedDate: String?,
    var LastName: String?,
    var FoodHabitsName: String?,
    var BodyTypeName: String?,
    var UserTypeName: String?,
    var CountryName: String?,
    var DeviceId: String?,
    var DrinkingStatusid: String?,
    var DrinkingStatusName: String?,
    var OccupationOther: String?,
    var Doshamid: String?,
    var CityId: String?,
    var PhysicalStatusName: String?,
    var Occupationid: String?,
    var MaritalStatusName: String?,
    var Matrimonial: String?,
    var TokenId: String?,
    var NakshatraName: String?,
    var Complexionid: String?,
    var FoodHabitsid: String?,
    var FirstName: String?,
    var LivingWithId: String?,
    var AboutMe: String?,
    var Qualificationid: String?,
    var EMail: String?,
    var Mobile: String?,
    var OccupationName: String?,
    var UserTypeId: String?,
    var CasteId: String?,
    var MatrialStatusid: String?,
    var PhysicalStatusid: String?,
    var LivingWithName: String?,
    var ReligionId: String?,
    var age: String?,
    val Height: String?,
    val Weight: String?,
    val OwnCarType: String?,
    val OwnHouseType: String?,
    val SmokingType: String?,
    val Distance: String?,
    val ImagesList: ArrayList<ImageObject>?,
    var latestChat: LatestChat? = null,
) : Parcelable