package vedam.subkuch.utils;

/**
 * Created by nansari on 7/18/2016.
 * For project RelayServices
 */
public enum ListItemClickAction {
    ESTIMATE_ACCEPT, ESTIMATE_REJECT, SEND_A_MESSAGE, SEE_PROFILE, SEE_REVIEWS, SEE_ESTIMATE_SUMMARY, SELECT, SELECT_SUBCATEGORY,
    SELECT_CATEGORY, SELECT_GALLERY_IMAGE, SELECT_DATE, SELECT_PROVIDER, SELECT_PACKAGE, SEE_DIAGNOSIS_FEE, SEE_PROVIDER_INFO,DELETE_GALLERY_IMAGE
}
